<?php
return $error = [
    "INVALID_PARAMETER"=>"201",
    "SECRET_KEY_WRONG"=>"202",
    "TOKEN_NOT_FOUND"=>"203",
    "SERVICE_NOT_FOUND"=>"204",
    "MERCHANT_NOT_FOUND"=>"205",
    "SYSTEM_ERROR"=>"206",
    "PARTNER_NOT_FOUND"=>"207",
    
    /*
     * login
     */
    "USERNAME_REQUIRED"=>"301",
    "PASSWORD_REQUIRED"=>"302",
    "USERNAME_OR_PASSWORD_WRONG"=>"303",
    "USER_INACTIVE"=>"304",
    // resend password
    "USER_NOT_FOUND"=>"305",
    // active code
    "ACTIVE_CODE_REQUIRED"=>"306",
    "ACTIVE_CODE_NOT_FOUND"=>"307",
    // change username
    "USERNAME_NEW_REQUIRED"=>"308",
    "USERNAME_NEW_EXIST"=>"309",
    "CONFIRM_PASSWORD_WRONG"=>"310",
    "USERNAME_PATTERN"=>"316",
    // change password
    "PASSWORD_NEW_REQUIRED"=>"311",
    "PASSWORD_NEW_CONFIRM_REQUIRED"=>"312",
    "PASSWORD_NEW_SHOULD_DIFFERENT_PASSWORD_NOW"=>"313",
    "PASSWORD_NEW_CONFIRM_WRONG"=>"314",
    "PASSWORD_PATTERN"=>"315",
    // register user
    "USERNAME_EXIST"=>"317",
    "PASSWORD_CONFIRM_REQUIRED"=>"318",
    "PASSWORD_CONFIRM_WRONG"=>"319",
    "EMAIL_REQUIRED"=>"320",
    "EMAIL_EXIST"=>"322",
    "MOBILE_REQUIRED"=>"321",
    "MOBILE_EXIST"=>"323",
    "EMAIL_OR_MOBILE_REQUIRED"=>"324",
    "USERNAME_INVALID"=>"325",
    "USER_EXIST"=>"326",
    "MERCHANT_HAVE_NOT_USER"=>"327",
    "PASSWORD_OLD_REQUIRED"=>"328",
    "PASSWORD_OLD_WRONG"=>"329",
    // common
    "DATA_NOT_FOUND"=>"330"
];
